baseURL: "https://zake1god.github.io"
languageCode: en-us
title: ZAKE
theme: PaperMod

menu:
  main:
    - identifier: about
      name: About
      url: about
      weight: 10
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: achievement
      name: Achievement
      url: /achievement
      weight: 30
    - identifier: contact
      name: Contact
      url: contact
      weight: 40
    # - identifier: search
    #   name: Search
    #   url: search
    #   weight: 40
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  # profileMode:
  #   enabled: true
  #   title: " "
  #   subtitle: Hi 👋! My name is **Zaki Zarkasih Al Mustafa** but you can call me zake. Im an Cyber Security Enthusiast from Indonesia 🇮🇩 Currently focussing learning Penetration Testing, but that doesn't mean I haven't learned anything else. <br><br> I studied a bit of BackEnd / FrontEnd / Networking and Graphic Design. Because in the world of the internet everything needs each other. 💻 <br><br> If you have any questions, don't hesitate to find me via the link below. <br><br>
  #   imageUrl: "home/zakewhite.jpg"
  #   imageWidth: 200
  #   imageHeight: 200
  homeInfoParams:
        Title: Welcome! 👋
        Content: This site contains information about me, my experience, and my achievements. <br> While that's all, it's unlikely that I will blog on this website. If you want to contact me, you can use the link below.
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:zkephl@pm.me"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/zaki-zarkasih-95ab31197"
    - name: "github"
      url: "https://github.com/zake1god"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
