baseURL: "https://zake1god.github.io"
languageCode: en-us
title: Zake
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: achievement
      name: Achievement
      url: /achievement
      weight: 30
    - identifier: terminal
      name: Terminal
      url: /Terminal
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Zaki Zarkasih Al Mustafa"
    subtitle: Hi 👋! I'm zake, an Cyber Security Enthusiast, living in Indonesia 🇮🇩. Currently focussing learning Penetration Testing. While doing hacking i'm using Kali Linux as my penetration OS. I graduated from STMIK Palcomtech in May, 2022. But got graduated party in Feb 2023 because my campus upgraded from STMIK to ITB. Previously, I did an internship at Diskominfo, South Sumatra Province, and then took my thesis at KPAI Palembang.<br><br><br>
    imageUrl: "home/zakewhite.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:zkephl@pm.me"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/zaki-zarkasih-95ab31197"
    - name: "github"
      url: "https://github.com/zake1god"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
